export const REALTIME_EVENTS = {
  CONNECTED: 'connected',
  ERROR: 'exception',
  PING: 'ping',
  PONG: 'pong',
  USER_ONLINE: 'user:online',
  USER_OFFLINE: 'user:offline',
  USERS_ONLINE: 'users:online',
  ROOM_JOIN: 'room:join',
  ROOM_JOINED: 'room:joined',
  ROOM_LEAVE: 'room:leave',
  ROOM_LEFT: 'room:left',
  ROOM_MEMBER_JOINED: 'room:member-joined',
  ROOM_MEMBER_LEFT: 'room:member-left',
  FRIEND_REQUEST_RECEIVED: 'friend-request:received',
  FRIEND_REQUEST_ACCEPTED: 'friend-request:accepted',
  FRIEND_REQUEST_REJECTED: 'friend-request:rejected',
  FRIEND_REMOVED: 'friend:removed',
  CONVERSATION_CREATED: 'conversation.created',
} as const;
