services:
  postgres:
    image: postgres:18
    container_name: transcendence-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: transcendence
      POSTGRES_DB: transcendence

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U transcendence -d transcendence",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: