name: Notify Discord on Pull Request

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ACTOR="${{ github.event.pull_request.user.login }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          PR_URL="${{ github.event.pull_request.html_url }}"

          if [ -n "$PR_BODY" ] && [ "$PR_BODY" != "null" ]; then
            DESCRIPTION=$(echo "$PR_BODY" | head -20 | head -c 1000)
          else
            DESCRIPTION="No pull request description."
          fi

          PAYLOAD=$(jq -n \
            --arg actor "$ACTOR" \
            --arg pr_number "$PR_NUMBER" \
            --arg title "$PR_TITLE" \
            --arg description "$DESCRIPTION" \
            --arg link "$PR_URL" \
            '
            {
              content:"",
              embeds:[
                {
                  title:("🔔 Pull Request #"+$pr_number+" is ready for review"),
                  url:$link,
                  color:5814783,

                  fields:[
                    {
                      name:"👤 Author",
                      value:$actor,
                      inline:true
                    },
                    {
                      name:"🔢 PR",
                      value:("#"+$pr_number),
                      inline:true
                    },
                    {
                      name:"📝 Title",
                      value:("```"+$title+"```"),
                      inline:false
                    },
                    {
                      name:"📖 Description",
                      value:("```"+$description+"```"),
                      inline:false
                    }
                  ],

                  footer:{
                    text:"transcendence"
                  }
                }
              ]
            }
            ')

          curl -f \
            -H "Content-Type: application/json" \
            -X POST \
            -d "$PAYLOAD" \
            "$DISCORD_WEBHOOK"